---
"on":
  pull_request:
  push:
    branches:
      - main
jobs:
  check-metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check Metadata
        uses: damacus/check-chef-metadata-action
