---
name: "Prevent file change reusable"

"on":
  workflow_call:
    inputs:
      metadata_pattern:
        description: Pattern of files to check for metadata changes
        required: false
        type: string
        default: metadata.rb
      metadata_trusted_authors:
        description: Comma-separated list of trusted authors for metadata changes
        required: false
        type: string
        default: bmhughes,damacus,kitchen-porter,MarkGibbons,ramereth,Stromweld,xorima
      workflow_pattern:
        description: Pattern of workflow files to monitor
        required: false
        type: string
        default: .github/workflows
      workflow_trusted_authors:
        description: Comma-separated list of trusted authors for workflow changes
        required: false
        type: string
        default: bmhughes,damacus,kitchen-porter,MarkGibbons,ramereth,Stromweld,xorima
      workflow_close_pr:
        description: Close the PR if workflow files change
        required: false
        type: boolean
        default: true
      workflow_allow_new_files:
        description: Allow new files to be added in the workflow directory
        required: false
        type: boolean
        default: false
    secrets:
      token:
        required: false

jobs:
  prevent-metadata-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Prevent metadata.rb file change
        uses: xalvarez/prevent-file-change-action@v3
        with:
          githubToken: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          pattern: ${{ inputs.metadata_pattern }}
          trustedAuthors: ${{ inputs.metadata_trusted_authors }}

  prevent-workflow-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Prevent workflow file change
        uses: xalvarez/prevent-file-change-action@v3
        with:
          githubToken: ${{ secrets.token || secrets.GITHUB_TOKEN }}
          pattern: ${{ inputs.workflow_pattern }}
          trustedAuthors: ${{ inputs.workflow_trusted_authors }}
          closePR: ${{ inputs.workflow_close_pr }}
          allowNewFiles: ${{ inputs.workflow_allow_new_files }}
