---
name: "Prevent file change"

"on":
  workflow_call:
    secrets:
      token: {required: true}

jobs:
  prevent-metadata-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Prevent metadata.rb file change
        uses: xalvarez/prevent-file-change-action@v2
        with:
          githubToken: ${{ secrets.token }}
          pattern: metadata.rb
          trustedAuthors: &maintainers bmhughes,damacus,kitchen-porter,MarkGibbons,ramereth,Stromweld,xorima

  prevent-workflow-change:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Prevent workflow file change
        uses: xalvarez/prevent-file-change-action@v2
        with:
          githubToken: ${{ secrets.token }}
          pattern: .github/workflows
          trustedAuthors: *maintainers
          closePR: true
          allowNewFiles: false
